version: "3.8"

services:
  nextjs-js-boilerplate:
    container_name: nextjs-js-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
